spring.application.name=fantasybackend

server.port=8080

spring.datasource.url=jdbc:mysql://rdsbetadbinmum.cdljsaivntv8.ap-south-1.rds.amazonaws.com:32660/fantasy_app?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=betadbuser
spring.datasource.password=betapass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jackson.datatype.datetime.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Kolkata

jwt.secret=change-this-to-at-least-32-characters-long-secret-key-2026
jwt.access-token-expiry-minutes=60
jwt.refresh-token-expiry-days=30

sportmonks.cricket-base-url=https://cricket.sportmonks.com/api/v2.0
sportmonks.token=aBJYz4MsSUtxjdqMH4WBZKNYomAJrxMI605wxnZqJqanns0iSYC1JrKJ5ZG7
sportmonks.ipl-league-id=1
sportmonks.upcoming-sync-days=30

app.cricket-sport-id=1

logging.level.org.springframework.security=DEBUG

app.otp.fixed-enabled=false
app.otp.fixed-value=081181
app.otp.expiry-minutes=5

app.team.max-players=11
app.team.max-from-one-side=7
app.team.credit-limit=100.0
app.team.default-player-credit=8.0

spring.mail.host=smtp.dreamhost.com
spring.mail.port=587
spring.mail.username=itsupport@hasbroclothing.com
spring.mail.password=EwG!uZ3^
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=itsupport@hasbroclothing.com